live_config_reload = true

[window]
padding = { x = 5, y = 3 }
dynamic_padding = true
resize_increments = true
dimensions = { columns = 176, lines = 40 }

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 12
offset = { x = -1, y = 0}

[colors.primary]
foreground = "#b9bcba"
background = "#1f1f1f"

[colors]
cursor = { cursor = "#f83e19" }
selection = { background = "#2a2d32" }

[colors.normal]
black = "#3a3d43"
red = "#be3f48"
green = "#879a3b"
yellow = "#c5a635"
blue = "#4f76a1"
magenta = "#855c8d"
cyan = "#578fa4"
white = "#b0bcba"

[colors.bright]
black = "#888987"
red = "#fb001f"
green = "#0f722f"
yellow = "#c47033"
blue = "#186de3"
magenta = "#fb0067"
cyan = "#2e706d"
white = "#fdffb9"

