contexts:
  default:
    defaultIde: none
    defaultProvider: docker
    options:
      DOTFILES_SCRIPT:
        userProvided: true
        value: install.sh
      DOTFILES_URL:
        userProvided: true
        value: https://github.com/mrshiister/dotfiles
      GPG_AGENT_FORWARDING:
        userProvided: true
        value: "true"
      SSH_INJECT_DOCKER_CREDENTIALS:
        userProvided: true
        value: "false"
      TELEMETRY:
        userProvided: true
        value: "false"
defaultContext: default
